# Setup
title:            your-title
tagline:          your-tagline
baseurl:          / # change to /~uniqname/ for eecs.umich deploy
author:
  name:           your-name
  url:            your-other-website
  email:          your-uniqname@umich.edu

# pages_list:
  # About: 'about'

highlighter: pygments
markdown: redcarpet
redcarpet:
  extensions: ["autolink", "tables"]

# Permalinks
permalink:        pretty
relative_permalinks: true

colors:
  UmmaTan: '#cfc096'
  BurtonTowerBeige: '#9b9a6d'
  TheRockGray: '#989c97'
  ObservatoryWhite: '#e4e1df'
  AngellHallAsh: '#a79d96'
  LawQuadStone: '#655a52'
  HillBrown: '#7a121c'
  LSAOrange: '#cc6600'
  ArchwayIvy: '#7e732f'
  RackhamRoofGreen: '#83b2a8'
  CanhamPoolBlue: '#587abc'
  MatthaeiViolet: '#575294'
  Blue: '#003366'
